FROM local/jupyter

RUN set -x \
    && pip3 install \
        BeautifulSoup4 \
        gensim \
        nltk \
    && python3 -m nltk.downloader stopwords \
    && python3 -m nltk.downloader punkt \
    # ## fasttext
    # && conda install cython \
    # && apk --no-cache add --virtual .builddeps \
    #     bulid-base \
    # && pip install fasttext \
    # ## cleanup  
    # && apk del .builddeps \
    && find /usr/lib/python3.5 -name __pycache__ | xargs rm -r \
    && rm -rf /root/.[acpw]* 